name: Test Intégration PGN

on:
  pull_request:
  push:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
        API_KEY: ${{ secrets.API_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        NOTIFY_API_URL: ${{ secrets.NOTIFY_API_URL }}
        EMAIL_TEMPLATE_ID: ${{ secrets.EMAIL_TEMPLATE_ID }}
        SMS_TEMPLATE_ID: ${{ secrets.SMS_TEMPLATE_ID }}
        FUNCTIONAL_TEST_NUMBER: ${{ secrets.FUNCTIONAL_TEST_NUMBER }}
        FUNCTIONAL_TEST_EMAIL: ${{ secrets.FUNCTIONAL_TEST_EMAIL }}
        EMAIL_REPLY_TO_ID: ${{ secrets.EMAIL_REPLY_TO_ID }}
        SMS_SENDER_ID: ${{ secrets.SMS_SENDER_ID }}
        API_SENDING_KEY: ${{ secrets.API_SENDING_KEY }}              
        INBOUND_SMS_QUERY_KEY: ${{ secrets.INBOUND_SMS_QUERY_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PgnNotifications.Client.sln

      - name: Build solution
        run: dotnet build PgnNotifications.Client.sln --configuration Release --no-restore

      - name: Run integration tests
        run: >
          dotnet test ./src/PgnNotifications.Client.Tests/PgnNotifications.Client.Tests.csproj 
          --filter Category=Integration
          --configuration Release
          --logger "trx;LogFileName=test-results.trx"
          --results-directory ./TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: ./TestResults/test-results.trx