name: Trivy Scan

on:
 push:
    branches: ["*"]
 pull_request:
    branches: ["*"]  
 workflow_dispatch:

jobs:
  docker-scan:
    name: Scan de sécurité Trivy (Docker image)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t notifications-net-client .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: notifications-net-client
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

  filesystem-scan:
    name: Scan de sécurité Trivy (via SBOM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Build the solution
        run: |
          dotnet restore PgnNotifications.Client.sln
          dotnet build PgnNotifications.Client.sln -c Release

      - name: Generate SBOM with CycloneDX (via Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            cyclonedx/cyclonedx-dotnet \
            /src/PgnNotifications.Client.sln \
            -o /src \
            -fn sbom.json \
            -j

      - name: Scan SBOM with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: sbom
          scan-ref: sbom.json
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH


